apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: default
spec:
  podSelector:
    matchLabels:
      pod: pod-1
      pod: pod-2
  policyTypes:
  - Ingress
  - Egress

#git clone https://github.com/jannucs/cks.git
